/* obcrypt C ABI — committed reference header.
 *
 * Generated by cbindgen from the Rust source — do not edit by hand.
 * Regenerate with:
 *   cbindgen --config cbindgen.toml --output include/obcrypt.h
 *
 * The binary counterpart to oboron's C ABI: where oboron passes
 * NUL-terminated strings, obcrypt passes (ptr, len) byte buffers,
 * so payloads may contain NUL, 0xFF, anything.
 *
 * Contract (see src/lib.rs for the full text):
 *  - Input buffers are (const uint8_t *ptr, size_t len); a null ptr
 *    is allowed only when len == 0.
 *  - `scheme` is a name string ("psiv", "dsiv", …), NUL-terminated.
 *    The *_hex_key entry points additionally take the key as a
 *    NUL-terminated 128-char hex string `key_hex`.
 *  - Each output buffer is heap-allocated and owned by the caller,
 *    who MUST release it with obcrypt_buffer_free(ptr, len), passing
 *    back the same (ptr, len). Never libc free.
 *  - Return is a status code: 0 = OBCRYPT_OK, < 0 = FFI-layer fault,
 *    > 0 = obcrypt error. On any nonzero return do NOT read *out;
 *    fetch a message with obcrypt_last_error().
 *  - OBCRYPT_ABI_VERSION marks the C ABI generation; it bumps only on
 *    an incompatible change to this surface, never on an ordinary
 *    release.
 */

#ifndef OBCRYPT_H
#define OBCRYPT_H

#include <stddef.h>
#include <stdint.h>

/**
 * Success.
 */
#define OBCRYPT_OK 0

/**
 * A required pointer argument was null (with a nonzero length).
 */
#define OBCRYPT_ERR_NULL_ARG -1

/**
 * The scheme name was not valid UTF-8.
 */
#define OBCRYPT_ERR_UTF8 -2

/**
 * The scheme name is not a scheme this build supports.
 */
#define OBCRYPT_ERR_BAD_SCHEME -3

/**
 * A panic was caught at the FFI boundary.
 */
#define OBCRYPT_ERR_PANIC -4

/**
 * obcrypt rejected the operation; see [`obcrypt_last_error`].
 */
#define OBCRYPT_ERR_OBCRYPT 1

/**
 * C ABI generation. Independent of the package version: this bumps
 * only on an *incompatible* change to the exported C surface (a
 * removed/renamed symbol, a changed signature or status-code
 * meaning), never on an ordinary release. The committed header is
 * the full contract; this is a coarse `#if`-able guard for
 * consumers (`#if OBCRYPT_ABI_VERSION != 1`).
 */
#define OBCRYPT_ABI_VERSION 1

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * The obcrypt-ffi package version as a static NUL-terminated C
 * string (matches `Cargo.toml`, e.g. `"0.1.0"`). The pointer is
 * borrowed and `'static` — never free it. This is the package
 * version, which moves every release; for the coarse ABI-stability
 * guard see the `OBCRYPT_ABI_VERSION` constant.
 */
const char *obcrypt_abi_version(void);

/**
 * Borrow this thread's last error message as a NUL-terminated C
 * string, or null if the last call on this thread succeeded.
 *
 * Valid only until the next `obcrypt_*` call on this thread; copy it
 * if you need to keep it. Do **not** free it.
 */
const char *obcrypt_last_error(void);

/**
 * Free a buffer this library returned through `(*out, *out_len)`.
 * Pass back the exact `(ptr, len)` you received. A null `ptr` is a
 * no-op; any other pointer, a wrong length, or a double free is
 * undefined behavior.
 */
void obcrypt_buffer_free(uint8_t *ptr, size_t len);

/**
 * Encrypt `plaintext` under the named `scheme` (e.g. `"psiv"`) with
 * a 64-byte `key`. Writes the payload to `(*out, *out_len)`.
 */
int32_t obcrypt_encrypt(const uint8_t *plaintext,
                        size_t plaintext_len,
                        const char *scheme,
                        const uint8_t *key,
                        size_t key_len,
                        uint8_t **out,
                        size_t *out_len);

/**
 * Decrypt `payload` under the named `scheme` (e.g. `"psiv"`) with a
 * 64-byte `key`. The output carries no marker, so the same scheme used
 * to encrypt must be named here; a wrong scheme fails the
 * authentication check. Writes the plaintext to `(*out, *out_len)`.
 */
int32_t obcrypt_decrypt(const uint8_t *payload,
                        size_t payload_len,
                        const char *scheme,
                        const uint8_t *key,
                        size_t key_len,
                        uint8_t **out,
                        size_t *out_len);

/**
 * Encrypt `plaintext` under the named `scheme` with the key given as
 * a NUL-terminated 128-character hex string (the canonical oboron
 * key form, what env vars and config files carry). The hex-key
 * counterpart of [`obcrypt_encrypt`] — identical buffer contract and
 * status codes; bad hex / wrong length is reported as
 * [`OBCRYPT_ERR_OBCRYPT`]. Writes the payload to `(*out, *out_len)`.
 */
int32_t obcrypt_encrypt_hex_key(const uint8_t *plaintext,
                                size_t plaintext_len,
                                const char *scheme,
                                const char *key_hex,
                                uint8_t **out,
                                size_t *out_len);

/**
 * Decrypt `payload` under the named `scheme` with the key given as a
 * NUL-terminated 128-character hex string. The hex-key counterpart
 * of [`obcrypt_decrypt`] — identical buffer contract and status
 * codes. The output carries no marker, so the same scheme used to
 * encrypt must be named; a wrong scheme fails the authentication
 * check. Writes the plaintext to `(*out, *out_len)`.
 */
int32_t obcrypt_decrypt_hex_key(const uint8_t *payload,
                                size_t payload_len,
                                const char *scheme,
                                const char *key_hex,
                                uint8_t **out,
                                size_t *out_len);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* OBCRYPT_H */
